void Debugging() {
  //  Serial.print(" mod: "); Serial.print(mod);
  //  Serial.print(" orientation_setpoint: "); Serial.print(orientation_setpoint);
  //  Serial.print(" silosetpoint: "); Serial.print(siloSetpoint);
  //  Serial.print(" Y Distance: "); Serial.print(y_distance);
  //  Serial.print(" silo: "); Serial.print( silo);
  //  Serial.print("  X Distance: "); Serial.print(x_distance);
  //  Serial.print(" Z Distance: "); Serial.print(z_distance);
  //  Serial.print(" Dist: "); Serial.print(dist);
  //  Serial.print(" signature: "); Serial.print(signature);
  //  Serial.print("low_Dist: "); Serial.print(low_val - dist);
  //  Serial.print(" siloFlag: "); Serial.print(siloFlag);
  //  Serial.print(" LSA_input: "); Serial.print(LSA_input);
  //  Serial.print(" tf_input: "); Serial.print(tf_input);
  //  Serial.print(" pixy_error: "); Serial.print(pixy_error);
  //  Serial.print(" silo_error: "); Serial.print(silo_error);
  //  Serial.print(" targetSilo: "); Serial.print(targetSilo);
  //  Serial.print(" Orientation: "); Serial.print(orientation);
  //  Serial.print(" StopTurnFlag: "); Serial.print(StopTurnFlag);
  //  Serial.print(" ballTurnFlag: "); Serial.print(ballTurnFlag);
  //  Serial.print(" CheckTimeFlag: "); Serial.print(CheckTimeFlag);
  //  Serial.print(" ballFlag: "); Serial.print(ballFlag);
  //  Serial.print(" modeFlag: "); Serial.print(modeFlag);
  //  Serial.print(" Rflag: "); Serial.print(Rflag);
  //  Serial.print(" siloFlag: "); Serial.print(siloFlag);
  //  Serial.print(" rollerStartFlag: "); Serial.print(rollerStartFlag);
  //  Serial.print(" SignatureID: "); Serial.print(SignatureID);
  //  Serial.print(" button_input: "); Serial.print(button_input);
  //  Serial.print(" button_input1: "); Serial.print(button_input1);
  //  Serial.print(" button_input2: "); Serial.print(button_input2);
  //  Serial.println();
}
